import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import Link from 'next/link';

import '@/style/global.css';
import style from '@/style/layout.main.module.css';
import IntlWrapper from '@/components/IntlWrapper';

import StoreProvider from '@/components/StoreProvider';

import { Providers } from '@/components/themesProviders';

import { cookies } from 'next/headers';

import ManifestLayout from './manifestLayout';

const robotoSans = Roboto({
    subsets: ['latin'],
    weight: ['400', '600', '700'],
    variable: '--font-roboto',
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    const cookiesStore = await cookies();

    const themeColor = cookiesStore.get('theme')?.value;

    // let lang = cookiesStore.get('language')?.value;

    // if (lang == undefined) {
    //     lang = 'ru';
    // }

    return (
        <html lang="ru" suppressHydrationWarning>
            <head>
                <meta name="google" content="notranslate" />
                <meta name="apple-mobile-web-app-title" content="Обмен файлами" />

                {themeColor == 'light' ? (
                    <meta name="theme-color" content="#ffffff" />
                ) : (
                    <meta name="theme-color" content="#000000" />
                )}

                <ManifestLayout />

                {/* <meta name="theme-color" content="#ffffff" media="(prefers-color-scheme: light)" />
                <meta name="theme-color" content="#000000" media="(prefers-color-scheme: dark)" /> */}
            </head>
            <body className={robotoSans.className}>
                <StoreProvider>
                    <IntlWrapper>
                        <div className={style.contenire}>
                            <div className={style.content}>
                                <Providers>{children}</Providers>
                            </div>
                        </div>
                    </IntlWrapper>
                </StoreProvider>
            </body>
        </html>
    );
}
